In [1]:
from Database.Database import DataFunFilm , DataFunDist
from gensim.similarities import WmdSimilarity
from Handlers.Descriptions import Model
from datetime import time
from tqdm import tqdm
import faiss
from sentence_transformers import SentenceTransformer
import numpy as np

In [2]:
distDB = DataFunDist()
db = DataFunFilm()
films = db.getTableDF()
model = Model()

In [3]:
films

id  kinopoisk_id    imdb_id              name_ru  \
0          1       1043658  tt4202274  Шоу Грязного Фрэнка   
1          2       1309325       None               Космос   
2          3         77044  tt0108778               Друзья   
3          4        972889  tt4926348          BadComedian   
4          5        674243       None      Счастливые люди   
...      ...           ...        ...                  ...   
66752  66753         83307  tt0041640        Мари из порта   
66753  66754        219369  tt0071859       Путешественник   
66754  66755         47614  tt0211372         Сын француза   
66755  66756        977755  tt9378362    Звоните ДиКаприо!   
66756  66757        256164  tt0804461    Смертный приговор   

               name_original  \
0      The Filthy Frank Show   
1                              
2                    Friends   
3                       None   
4                       None   
...                      ...   
66752       La Marie du port   
66753               Mossafer   
66754    Le fils du Français   
66755                   None   
66756         Death Sentence   

                                              poster_url  rating_imdb  \
0      https://kinopoiskapiunofficial.tech/images/pos...          9.7   
1      https://kinopoiskapiunofficial.tech/images/pos...          NaN   
2      https://kinopoiskapiunofficial.tech/images/pos...          9.0   
3      https://kinopoiskapiunofficial.tech/images/pos...          7.7   
4      https://kinopoiskapiunofficial.tech/images/pos...          8.8   
...                                                  ...          ...   
66752  https://kinopoiskapiunofficial.tech/images/pos...          6.7   
66753  https://kinopoiskapiunofficial.tech/images/pos...          7.5   
66754  https://kinopoiskapiunofficial.tech/images/pos...          5.0   
66755  https://kinopoiskapiunofficial.tech/images/pos...          6.7   
66756  https://kinopoiskapiunofficial.tech/images/pos...          6.7   

       rating_imdb_vote_count  rating_film_critics  rating_critics_vote_count  \
0                       32929                  NaN                          0   
1                           0                  NaN                          0   
2                      937875                  NaN                          0   
3                         793                  NaN                          0   
4                         120                  NaN                          0   
...                       ...                  ...                        ...   
66752                     395                  NaN                          0   
66753                    1695                  NaN                          0   
66754                     282                  NaN                          0   
66755                     496                  NaN                          0   
66756                   71395                  4.2                        113   

         year  film_length                                  genres  \
0      2011.0         12.0  фэнтези комедия музыка короткометражка   
1      2019.0          NaN                          документальный   
2      1994.0         22.0                       мелодрама комедия   
3      2011.0          NaN                                 комедия   
4      2008.0         55.0                          документальный   
...       ...          ...                                     ...   
66752  1950.0         88.0                         драма мелодрама   
66753  1974.0         83.0                                   драма   
66754  1999.0        107.0            приключения комедия семейный   
66755  2018.0         48.0                           драма комедия   
66756  2007.0        105.0           триллер драма криминал боевик   

                                        web_url                     slogan  \
0      https://www.kinopoisk.ru/series/1043658/                       None   
1      https://www.kinopoisk.ru/s

In [4]:
model_descr = list(films["prepare_description"])

In [5]:
description = list(map(lambda x : x.split(),list(films["prepare_description"])))
description[0]

['шоу_PROPN',
 'повествовать_VERB',
 'о_ADP',
 'героический_ADJ',
 'борьба_NOUN',
 'сэр_NOUN',
 'фрэнсис_PROPN',
 'грязной_ADJ',
 'и_CCONJ',
 'он_PRON',
 'верный_ADJ',
 'друг_NOUN',
 'против_ADP',
 'зловещий_ADJ',
 'темный_ADJ',
 'бог_NOUN',
 'в_ADP',
 'сюрреалистический_ADJ',
 'омнивселенной_NOUN']

In [6]:
keys = model.model.key_to_index.keys()

In [64]:
desc = []
for i in tqdm(range(len(description))):
    sent = []
    for word in description[i]:
        if word in keys:
            sent.append(model.model[word])
    desc.append(np.array(sent))
desc = np.array(desc, dtype="object")
desc[0]

100%|██████████| 66757/66757 [00:16<00:00, 4030.19it/s]


array([[ 0.6778329 , -2.1406288 ,  0.23269792, ..., -1.0962808 ,
        -1.3404318 ,  0.877907  ],
       [-0.94731104, -0.99548364, -1.3306068 , ..., -2.2272267 ,
         0.94829875,  0.18321598],
       [-1.4011941 , -0.9699115 ,  0.3996764 , ..., -0.5424539 ,
        -0.00978736, -1.1246781 ],
       ...,
       [-2.0932076 , -0.3544742 ,  0.946783  , ...,  0.26891842,
        -3.046455  , -1.3474947 ],
       [-0.98503155, -1.751591  ,  0.51085794, ..., -2.618336  ,
        -2.2761512 , -3.376037  ],
       [ 0.12781557, -0.1343181 , -0.0792335 , ..., -0.783275  ,
         1.2887568 , -1.6977879 ]], dtype=float32)

In [9]:
model = SentenceTransformer('all-mpnet-base-v2')

Downloading:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/10.1k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/571 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/349 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/239 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/363 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.1k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [11]:
%%time
sentence_embeddings = model.encode(model_descr)
sentence_embeddings.shape


KeyboardInterrupt



In [66]:
index = faiss.IndexHNSW(model.model.vector_size)
index.add(desc)

ValueError: not enough values to unpack (expected 2, got 1)

In [ ]:
index.add(model.model.vectors)

In [50]:
index.ntotal

249333

In [51]:
index.is_trained

True

In [52]:
k = 10
xq = desc[0]

In [53]:
%%time
D, I = index.search(xq, k)  # search
print(I)

[[ 13430  60244  88831 176302]
 [  7657  19040    921  13982]
 [  6586  84816  30647  12363]
 [   429   4904  13797  29807]
 [  3734   5634   4603   7066]
 [ 16317  21654  63775  14863]
 [  1882  20924  16784   3831]
 [   146  15344  77577  42360]
 [ 12816  57420   8164  60713]
 [  1457   2984   1775   1727]
 [   881   5384   5636    994]
 [ 30176 131517  53329 109166]]
CPU times: total: 1.5 s
Wall time: 150 ms


In [47]:
films.iloc[1828]

id                                                                        1829
kinopoisk_id                                                            134703
imdb_id                                                              tt0347718
name_ru                                                            Другие миры
name_original                                                  D'autres mondes
poster_url                   https://kinopoiskapiunofficial.tech/images/pos...
rating_imdb                                                                7.6
rating_imdb_vote_count                                                     354
rating_film_critics                                                        NaN
rating_critics_vote_count                                                    0
year                                                                    2004.0
film_length                                                               90.0
genres                                              